<!DOCTYPE html>
<html lang="fa">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="description"
    content="فروش انواع پارچه های پرشیا با رنگبندی متنوع در کالیته های 90 تایی، جهت تهیه روپوش و لباس زنانه و دخترانه" />
  <meta name="author" content="Babak Ashtari" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- for SEO purposes -->
  <!-- open graph meta tags for SEO -->
  <meta property="og:title" content="صنایع نساجی کوثربافت نوین-پرشیا" />
  <meta property="og:site_name" content="کوثربافت نوین" />
  <meta property="og:url" content="https://kowsarbaft.ir/KalitePersia.html" />
  <meta property="og:description"
    content="فروش پارچه های پرشیا، ارائه کالیته پرشیا رنگبندی، جهت تهیه روپوش و لباس زنانه و دخترانه، کالیته پرشیا 90 رنگی" />
  <meta property="og:locale:alternate" content="fa_IR" />
  <meta property="og:type" content="product" />
  <meta property="og:image" content="https://kowsarbaft.ir/images/logos/kowsarbaftGraftImage.jpg" />
  <link rel="shortcut icon" href="images/logos/kowsarbaftBrownLogo.png" type="image/x-icon" />
  <!-- font awesome -->
  <link rel="stylesheet" href="CSS/all.min.css" />
  <!-- this is how I normalize my file using an external css -->
  <link rel="stylesheet" href="https://necolas.github.io/normalize.css/latest/normalize.css" />
  <title>صنایع نساجی کوثر بافت نوین - کالیه پرشیا</title>
  <link rel="stylesheet" href="php/php_css/header.css">
  <link rel="stylesheet" href="php/php_css/footer.css">  
  <link rel="stylesheet" href="CSS/KalitePersia.css" />
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <![endif]-->
</head>

<body onload="hideBar()">
<?php require "php/header.php" ?>
<main>
    <section>
      <!-- first container -->
      <h1>:کالیته رنگ های پرشیا</h1>
      <div class="container">
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
        <div>
          <div></div>
          <p>
            <a href="#"></a>
          </p>
        </div>
      </div>
    </section>
    <div id="radio-container">
      <span onclick="prevnext(-1)">&lt;</span>
      <label for="">
        <input type="radio" name="selector" id="first" />
        <div onclick="checker(event)"></div>
      </label>
      <span onclick="prevnext(1)">&gt;</span>
    </div>
  </main>
<?php require "php/footer.php" ?>
  
  <script src="JS/KalitePersia.js"></script>
  <script src="php/php_js/header.js"></script>
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Product",
        "name": "پرشیا",
        "description": "پارچه پرشیا، ارائه کالیته پرشیا رنگبندی، جهت تهیه روپوش و لباس زنانه و دخترانه، کالیته پرشیا 90 رنگی",
        "url": "http://www.kowsarbaft.ir/KalitePersia.html",
        "brand": {
          "@type": "Brand",
          "name": "کوثر بافت نوین",
          "logo": "http://www.googleusercontent.com/images/logos/kowsarbaftMainLogo.png"
        },
        "offers": {
          "@type": "Offer",
          <!-- "price": "9.99" -->
        }
      }
    </script>
</body>

</html>